version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: is-db 
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/:/var/lib/postgresql/data/
