// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.protos;

public final class School {
  private School() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Timestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Timestamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Teacher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\005model\"c\n\tTimestamp\022\014\n\004yea" +
      "r\030\001 \002(\005\022\r\n\005month\030\002 \002(\005\022\013\n\003day\030\003 \002(\005\022\014\n\004h" +
      "our\030\004 \002(\005\022\016\n\006minute\030\005 \002(\005\022\016\n\006second\030\006 \002(" +
      "\005\"\252\001\n\007Student\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022" +
      "\023\n\013phoneNumber\030\003 \002(\005\022\017\n\007address\030\004 \002(\t\022\016\n" +
      "\006gender\030\005 \002(\t\022#\n\tbirthDate\030\006 \002(\0132\020.model" +
      ".Timestamp\022*\n\020registrationDate\030\007 \002(\0132\020.m" +
      "odel.Timestamp\"\220\001\n\007Teacher\022\n\n\002id\030\001 \002(\005\022\014" +
      "\n\004name\030\002 \002(\t\022\023\n\013phoneNumber\030\003 \002(\005\022#\n\tbir" +
      "thDate\030\004 \002(\0132\020.model.Timestamp\022\017\n\007addres" +
      "s\030\005 \002(\t\022 \n\010students\030\006 \003(\0132\016.model.Studen" +
      "tB\034\n\020uc.mei.is.protosB\006SchoolP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_model_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Timestamp_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Hour", "Minute", "Second", });
    internal_static_model_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "PhoneNumber", "Address", "Gender", "BirthDate", "RegistrationDate", });
    internal_static_model_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", "PhoneNumber", "BirthDate", "Address", "Students", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
