// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.protos;

/**
 * Protobuf type {@code model.Student}
 */
public final class Student extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.Student)
    StudentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Student.newBuilder() to construct.
  private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Student() {
    name_ = "";
    address_ = "";
    gender_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Student();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Student(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            phoneNumber_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            address_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            gender_ = bs;
            break;
          }
          case 50: {
            uc.mei.is.protos.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) != 0)) {
              subBuilder = birthDate_.toBuilder();
            }
            birthDate_ = input.readMessage(uc.mei.is.protos.Timestamp.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(birthDate_);
              birthDate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          case 58: {
            uc.mei.is.protos.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000040) != 0)) {
              subBuilder = registrationDate_.toBuilder();
            }
            registrationDate_ = input.readMessage(uc.mei.is.protos.Timestamp.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(registrationDate_);
              registrationDate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000040;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.protos.School.internal_static_model_Student_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.protos.School.internal_static_model_Student_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.protos.Student.class, uc.mei.is.protos.Student.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 3;
  private int phoneNumber_;
  /**
   * <code>required int32 phoneNumber = 3;</code>
   * @return Whether the phoneNumber field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNumber() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 phoneNumber = 3;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public int getPhoneNumber() {
    return phoneNumber_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object address_;
  /**
   * <code>required string address = 4;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string address = 4;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string address = 4;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 5;
  private volatile java.lang.Object gender_;
  /**
   * <code>required string gender = 5;</code>
   * @return Whether the gender field is set.
   */
  @java.lang.Override
  public boolean hasGender() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required string gender = 5;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gender_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string gender = 5;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 6;
  private uc.mei.is.protos.Timestamp birthDate_;
  /**
   * <code>required .model.Timestamp birthDate = 6;</code>
   * @return Whether the birthDate field is set.
   */
  @java.lang.Override
  public boolean hasBirthDate() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required .model.Timestamp birthDate = 6;</code>
   * @return The birthDate.
   */
  @java.lang.Override
  public uc.mei.is.protos.Timestamp getBirthDate() {
    return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
  }
  /**
   * <code>required .model.Timestamp birthDate = 6;</code>
   */
  @java.lang.Override
  public uc.mei.is.protos.TimestampOrBuilder getBirthDateOrBuilder() {
    return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
  }

  public static final int REGISTRATIONDATE_FIELD_NUMBER = 7;
  private uc.mei.is.protos.Timestamp registrationDate_;
  /**
   * <code>required .model.Timestamp registrationDate = 7;</code>
   * @return Whether the registrationDate field is set.
   */
  @java.lang.Override
  public boolean hasRegistrationDate() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>required .model.Timestamp registrationDate = 7;</code>
   * @return The registrationDate.
   */
  @java.lang.Override
  public uc.mei.is.protos.Timestamp getRegistrationDate() {
    return registrationDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : registrationDate_;
  }
  /**
   * <code>required .model.Timestamp registrationDate = 7;</code>
   */
  @java.lang.Override
  public uc.mei.is.protos.TimestampOrBuilder getRegistrationDateOrBuilder() {
    return registrationDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : registrationDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPhoneNumber()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAddress()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGender()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBirthDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRegistrationDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBirthDate().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getRegistrationDate().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, phoneNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gender_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getBirthDate());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getRegistrationDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, phoneNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gender_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getBirthDate());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getRegistrationDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.protos.Student)) {
      return super.equals(obj);
    }
    uc.mei.is.protos.Student other = (uc.mei.is.protos.Student) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasPhoneNumber() != other.hasPhoneNumber()) return false;
    if (hasPhoneNumber()) {
      if (getPhoneNumber()
          != other.getPhoneNumber()) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasGender() != other.hasGender()) return false;
    if (hasGender()) {
      if (!getGender()
          .equals(other.getGender())) return false;
    }
    if (hasBirthDate() != other.hasBirthDate()) return false;
    if (hasBirthDate()) {
      if (!getBirthDate()
          .equals(other.getBirthDate())) return false;
    }
    if (hasRegistrationDate() != other.hasRegistrationDate()) return false;
    if (hasRegistrationDate()) {
      if (!getRegistrationDate()
          .equals(other.getRegistrationDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasPhoneNumber()) {
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasGender()) {
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
    }
    if (hasBirthDate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDate().hashCode();
    }
    if (hasRegistrationDate()) {
      hash = (37 * hash) + REGISTRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.protos.Student parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Student parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Student parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Student parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Student parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Student parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Student parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Student parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Student parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Student parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Student parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Student parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.protos.Student prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.Student}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.Student)
      uc.mei.is.protos.StudentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.protos.School.internal_static_model_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.protos.School.internal_static_model_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.protos.Student.class, uc.mei.is.protos.Student.Builder.class);
    }

    // Construct using uc.mei.is.protos.Student.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBirthDateFieldBuilder();
        getRegistrationDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      phoneNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      gender_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (birthDateBuilder_ == null) {
        birthDate_ = null;
      } else {
        birthDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
      } else {
        registrationDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.protos.School.internal_static_model_Student_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.protos.Student getDefaultInstanceForType() {
      return uc.mei.is.protos.Student.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.protos.Student build() {
      uc.mei.is.protos.Student result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.protos.Student buildPartial() {
      uc.mei.is.protos.Student result = new uc.mei.is.protos.Student(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.phoneNumber_ = phoneNumber_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.address_ = address_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.gender_ = gender_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        if (birthDateBuilder_ == null) {
          result.birthDate_ = birthDate_;
        } else {
          result.birthDate_ = birthDateBuilder_.build();
        }
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        if (registrationDateBuilder_ == null) {
          result.registrationDate_ = registrationDate_;
        } else {
          result.registrationDate_ = registrationDateBuilder_.build();
        }
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.protos.Student) {
        return mergeFrom((uc.mei.is.protos.Student)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.protos.Student other) {
      if (other == uc.mei.is.protos.Student.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasPhoneNumber()) {
        setPhoneNumber(other.getPhoneNumber());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000008;
        address_ = other.address_;
        onChanged();
      }
      if (other.hasGender()) {
        bitField0_ |= 0x00000010;
        gender_ = other.gender_;
        onChanged();
      }
      if (other.hasBirthDate()) {
        mergeBirthDate(other.getBirthDate());
      }
      if (other.hasRegistrationDate()) {
        mergeRegistrationDate(other.getRegistrationDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasName()) {
        return false;
      }
      if (!hasPhoneNumber()) {
        return false;
      }
      if (!hasAddress()) {
        return false;
      }
      if (!hasGender()) {
        return false;
      }
      if (!hasBirthDate()) {
        return false;
      }
      if (!hasRegistrationDate()) {
        return false;
      }
      if (!getBirthDate().isInitialized()) {
        return false;
      }
      if (!getRegistrationDate().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.protos.Student parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.protos.Student) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private int phoneNumber_ ;
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return Whether the phoneNumber field is set.
     */
    @java.lang.Override
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return The phoneNumber.
     */
    @java.lang.Override
    public int getPhoneNumber() {
      return phoneNumber_;
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(int value) {
      bitField0_ |= 0x00000004;
      phoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>required string address = 4;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string address = 4;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string address = 4;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string address = 4;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string address = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>required string address = 4;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      address_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>required string gender = 5;</code>
     * @return Whether the gender field is set.
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string gender = 5;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gender_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string gender = 5;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string gender = 5;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string gender = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      bitField0_ = (bitField0_ & ~0x00000010);
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>required string gender = 5;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      gender_ = value;
      onChanged();
      return this;
    }

    private uc.mei.is.protos.Timestamp birthDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> birthDateBuilder_;
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     * @return Whether the birthDate field is set.
     */
    public boolean hasBirthDate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     * @return The birthDate.
     */
    public uc.mei.is.protos.Timestamp getBirthDate() {
      if (birthDateBuilder_ == null) {
        return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
      } else {
        return birthDateBuilder_.getMessage();
      }
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public Builder setBirthDate(uc.mei.is.protos.Timestamp value) {
      if (birthDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        birthDate_ = value;
        onChanged();
      } else {
        birthDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public Builder setBirthDate(
        uc.mei.is.protos.Timestamp.Builder builderForValue) {
      if (birthDateBuilder_ == null) {
        birthDate_ = builderForValue.build();
        onChanged();
      } else {
        birthDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public Builder mergeBirthDate(uc.mei.is.protos.Timestamp value) {
      if (birthDateBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
            birthDate_ != null &&
            birthDate_ != uc.mei.is.protos.Timestamp.getDefaultInstance()) {
          birthDate_ =
            uc.mei.is.protos.Timestamp.newBuilder(birthDate_).mergeFrom(value).buildPartial();
        } else {
          birthDate_ = value;
        }
        onChanged();
      } else {
        birthDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public Builder clearBirthDate() {
      if (birthDateBuilder_ == null) {
        birthDate_ = null;
        onChanged();
      } else {
        birthDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public uc.mei.is.protos.Timestamp.Builder getBirthDateBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getBirthDateFieldBuilder().getBuilder();
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    public uc.mei.is.protos.TimestampOrBuilder getBirthDateOrBuilder() {
      if (birthDateBuilder_ != null) {
        return birthDateBuilder_.getMessageOrBuilder();
      } else {
        return birthDate_ == null ?
            uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
      }
    }
    /**
     * <code>required .model.Timestamp birthDate = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> 
        getBirthDateFieldBuilder() {
      if (birthDateBuilder_ == null) {
        birthDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder>(
                getBirthDate(),
                getParentForChildren(),
                isClean());
        birthDate_ = null;
      }
      return birthDateBuilder_;
    }

    private uc.mei.is.protos.Timestamp registrationDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> registrationDateBuilder_;
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     * @return Whether the registrationDate field is set.
     */
    public boolean hasRegistrationDate() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     * @return The registrationDate.
     */
    public uc.mei.is.protos.Timestamp getRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        return registrationDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : registrationDate_;
      } else {
        return registrationDateBuilder_.getMessage();
      }
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public Builder setRegistrationDate(uc.mei.is.protos.Timestamp value) {
      if (registrationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        registrationDate_ = value;
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public Builder setRegistrationDate(
        uc.mei.is.protos.Timestamp.Builder builderForValue) {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = builderForValue.build();
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public Builder mergeRegistrationDate(uc.mei.is.protos.Timestamp value) {
      if (registrationDateBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
            registrationDate_ != null &&
            registrationDate_ != uc.mei.is.protos.Timestamp.getDefaultInstance()) {
          registrationDate_ =
            uc.mei.is.protos.Timestamp.newBuilder(registrationDate_).mergeFrom(value).buildPartial();
        } else {
          registrationDate_ = value;
        }
        onChanged();
      } else {
        registrationDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public Builder clearRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
        onChanged();
      } else {
        registrationDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public uc.mei.is.protos.Timestamp.Builder getRegistrationDateBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getRegistrationDateFieldBuilder().getBuilder();
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    public uc.mei.is.protos.TimestampOrBuilder getRegistrationDateOrBuilder() {
      if (registrationDateBuilder_ != null) {
        return registrationDateBuilder_.getMessageOrBuilder();
      } else {
        return registrationDate_ == null ?
            uc.mei.is.protos.Timestamp.getDefaultInstance() : registrationDate_;
      }
    }
    /**
     * <code>required .model.Timestamp registrationDate = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> 
        getRegistrationDateFieldBuilder() {
      if (registrationDateBuilder_ == null) {
        registrationDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder>(
                getRegistrationDate(),
                getParentForChildren(),
                isClean());
        registrationDate_ = null;
      }
      return registrationDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.Student)
  }

  // @@protoc_insertion_point(class_scope:model.Student)
  private static final uc.mei.is.protos.Student DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.protos.Student();
  }

  public static uc.mei.is.protos.Student getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
      PARSER = new com.google.protobuf.AbstractParser<Student>() {
    @java.lang.Override
    public Student parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Student(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Student> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Student> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.protos.Student getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

