// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.protos;

/**
 * Protobuf type {@code model.Teacher}
 */
public final class Teacher extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.Teacher)
    TeacherOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Teacher.newBuilder() to construct.
  private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Teacher() {
    name_ = "";
    address_ = "";
    students_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Teacher();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Teacher(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            phoneNumber_ = input.readInt32();
            break;
          }
          case 34: {
            uc.mei.is.protos.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) != 0)) {
              subBuilder = birthDate_.toBuilder();
            }
            birthDate_ = input.readMessage(uc.mei.is.protos.Timestamp.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(birthDate_);
              birthDate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            address_ = bs;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              students_ = new java.util.ArrayList<uc.mei.is.protos.Student>();
              mutable_bitField0_ |= 0x00000020;
            }
            students_.add(
                input.readMessage(uc.mei.is.protos.Student.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        students_ = java.util.Collections.unmodifiableList(students_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.protos.School.internal_static_model_Teacher_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.protos.School.internal_static_model_Teacher_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.protos.Teacher.class, uc.mei.is.protos.Teacher.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 3;
  private int phoneNumber_;
  /**
   * <code>required int32 phoneNumber = 3;</code>
   * @return Whether the phoneNumber field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNumber() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 phoneNumber = 3;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public int getPhoneNumber() {
    return phoneNumber_;
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 4;
  private uc.mei.is.protos.Timestamp birthDate_;
  /**
   * <code>required .model.Timestamp birthDate = 4;</code>
   * @return Whether the birthDate field is set.
   */
  @java.lang.Override
  public boolean hasBirthDate() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required .model.Timestamp birthDate = 4;</code>
   * @return The birthDate.
   */
  @java.lang.Override
  public uc.mei.is.protos.Timestamp getBirthDate() {
    return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
  }
  /**
   * <code>required .model.Timestamp birthDate = 4;</code>
   */
  @java.lang.Override
  public uc.mei.is.protos.TimestampOrBuilder getBirthDateOrBuilder() {
    return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>required string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENTS_FIELD_NUMBER = 6;
  private java.util.List<uc.mei.is.protos.Student> students_;
  /**
   * <code>repeated .model.Student students = 6;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.protos.Student> getStudentsList() {
    return students_;
  }
  /**
   * <code>repeated .model.Student students = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.protos.StudentOrBuilder> 
      getStudentsOrBuilderList() {
    return students_;
  }
  /**
   * <code>repeated .model.Student students = 6;</code>
   */
  @java.lang.Override
  public int getStudentsCount() {
    return students_.size();
  }
  /**
   * <code>repeated .model.Student students = 6;</code>
   */
  @java.lang.Override
  public uc.mei.is.protos.Student getStudents(int index) {
    return students_.get(index);
  }
  /**
   * <code>repeated .model.Student students = 6;</code>
   */
  @java.lang.Override
  public uc.mei.is.protos.StudentOrBuilder getStudentsOrBuilder(
      int index) {
    return students_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPhoneNumber()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBirthDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAddress()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBirthDate().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getStudentsCount(); i++) {
      if (!getStudents(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, phoneNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getBirthDate());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    for (int i = 0; i < students_.size(); i++) {
      output.writeMessage(6, students_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, phoneNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBirthDate());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    for (int i = 0; i < students_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, students_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.protos.Teacher)) {
      return super.equals(obj);
    }
    uc.mei.is.protos.Teacher other = (uc.mei.is.protos.Teacher) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasPhoneNumber() != other.hasPhoneNumber()) return false;
    if (hasPhoneNumber()) {
      if (getPhoneNumber()
          != other.getPhoneNumber()) return false;
    }
    if (hasBirthDate() != other.hasBirthDate()) return false;
    if (hasBirthDate()) {
      if (!getBirthDate()
          .equals(other.getBirthDate())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getStudentsList()
        .equals(other.getStudentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasPhoneNumber()) {
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber();
    }
    if (hasBirthDate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDate().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getStudentsCount() > 0) {
      hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getStudentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.protos.Teacher parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Teacher parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Teacher parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Teacher parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Teacher parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.protos.Teacher prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.Teacher}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.Teacher)
      uc.mei.is.protos.TeacherOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.protos.School.internal_static_model_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.protos.School.internal_static_model_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.protos.Teacher.class, uc.mei.is.protos.Teacher.Builder.class);
    }

    // Construct using uc.mei.is.protos.Teacher.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBirthDateFieldBuilder();
        getStudentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      phoneNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (birthDateBuilder_ == null) {
        birthDate_ = null;
      } else {
        birthDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.protos.School.internal_static_model_Teacher_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.protos.Teacher getDefaultInstanceForType() {
      return uc.mei.is.protos.Teacher.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.protos.Teacher build() {
      uc.mei.is.protos.Teacher result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.protos.Teacher buildPartial() {
      uc.mei.is.protos.Teacher result = new uc.mei.is.protos.Teacher(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.phoneNumber_ = phoneNumber_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (birthDateBuilder_ == null) {
          result.birthDate_ = birthDate_;
        } else {
          result.birthDate_ = birthDateBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.address_ = address_;
      if (studentsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          students_ = java.util.Collections.unmodifiableList(students_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.students_ = students_;
      } else {
        result.students_ = studentsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.protos.Teacher) {
        return mergeFrom((uc.mei.is.protos.Teacher)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.protos.Teacher other) {
      if (other == uc.mei.is.protos.Teacher.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasPhoneNumber()) {
        setPhoneNumber(other.getPhoneNumber());
      }
      if (other.hasBirthDate()) {
        mergeBirthDate(other.getBirthDate());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      if (studentsBuilder_ == null) {
        if (!other.students_.isEmpty()) {
          if (students_.isEmpty()) {
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureStudentsIsMutable();
            students_.addAll(other.students_);
          }
          onChanged();
        }
      } else {
        if (!other.students_.isEmpty()) {
          if (studentsBuilder_.isEmpty()) {
            studentsBuilder_.dispose();
            studentsBuilder_ = null;
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000020);
            studentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentsFieldBuilder() : null;
          } else {
            studentsBuilder_.addAllMessages(other.students_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasName()) {
        return false;
      }
      if (!hasPhoneNumber()) {
        return false;
      }
      if (!hasBirthDate()) {
        return false;
      }
      if (!hasAddress()) {
        return false;
      }
      if (!getBirthDate().isInitialized()) {
        return false;
      }
      for (int i = 0; i < getStudentsCount(); i++) {
        if (!getStudents(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.protos.Teacher parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.protos.Teacher) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private int phoneNumber_ ;
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return Whether the phoneNumber field is set.
     */
    @java.lang.Override
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return The phoneNumber.
     */
    @java.lang.Override
    public int getPhoneNumber() {
      return phoneNumber_;
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(int value) {
      bitField0_ |= 0x00000004;
      phoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 phoneNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneNumber_ = 0;
      onChanged();
      return this;
    }

    private uc.mei.is.protos.Timestamp birthDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> birthDateBuilder_;
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     * @return Whether the birthDate field is set.
     */
    public boolean hasBirthDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     * @return The birthDate.
     */
    public uc.mei.is.protos.Timestamp getBirthDate() {
      if (birthDateBuilder_ == null) {
        return birthDate_ == null ? uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
      } else {
        return birthDateBuilder_.getMessage();
      }
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public Builder setBirthDate(uc.mei.is.protos.Timestamp value) {
      if (birthDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        birthDate_ = value;
        onChanged();
      } else {
        birthDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public Builder setBirthDate(
        uc.mei.is.protos.Timestamp.Builder builderForValue) {
      if (birthDateBuilder_ == null) {
        birthDate_ = builderForValue.build();
        onChanged();
      } else {
        birthDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public Builder mergeBirthDate(uc.mei.is.protos.Timestamp value) {
      if (birthDateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            birthDate_ != null &&
            birthDate_ != uc.mei.is.protos.Timestamp.getDefaultInstance()) {
          birthDate_ =
            uc.mei.is.protos.Timestamp.newBuilder(birthDate_).mergeFrom(value).buildPartial();
        } else {
          birthDate_ = value;
        }
        onChanged();
      } else {
        birthDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public Builder clearBirthDate() {
      if (birthDateBuilder_ == null) {
        birthDate_ = null;
        onChanged();
      } else {
        birthDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public uc.mei.is.protos.Timestamp.Builder getBirthDateBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getBirthDateFieldBuilder().getBuilder();
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    public uc.mei.is.protos.TimestampOrBuilder getBirthDateOrBuilder() {
      if (birthDateBuilder_ != null) {
        return birthDateBuilder_.getMessageOrBuilder();
      } else {
        return birthDate_ == null ?
            uc.mei.is.protos.Timestamp.getDefaultInstance() : birthDate_;
      }
    }
    /**
     * <code>required .model.Timestamp birthDate = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder> 
        getBirthDateFieldBuilder() {
      if (birthDateBuilder_ == null) {
        birthDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            uc.mei.is.protos.Timestamp, uc.mei.is.protos.Timestamp.Builder, uc.mei.is.protos.TimestampOrBuilder>(
                getBirthDate(),
                getParentForChildren(),
                isClean());
        birthDate_ = null;
      }
      return birthDateBuilder_;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>required string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>required string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }

    private java.util.List<uc.mei.is.protos.Student> students_ =
      java.util.Collections.emptyList();
    private void ensureStudentsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        students_ = new java.util.ArrayList<uc.mei.is.protos.Student>(students_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.protos.Student, uc.mei.is.protos.Student.Builder, uc.mei.is.protos.StudentOrBuilder> studentsBuilder_;

    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public java.util.List<uc.mei.is.protos.Student> getStudentsList() {
      if (studentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(students_);
      } else {
        return studentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public int getStudentsCount() {
      if (studentsBuilder_ == null) {
        return students_.size();
      } else {
        return studentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public uc.mei.is.protos.Student getStudents(int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);
      } else {
        return studentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder setStudents(
        int index, uc.mei.is.protos.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.set(index, value);
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder setStudents(
        int index, uc.mei.is.protos.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder addStudents(uc.mei.is.protos.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder addStudents(
        int index, uc.mei.is.protos.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(index, value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder addStudents(
        uc.mei.is.protos.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder addStudents(
        int index, uc.mei.is.protos.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder addAllStudents(
        java.lang.Iterable<? extends uc.mei.is.protos.Student> values) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, students_);
        onChanged();
      } else {
        studentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder clearStudents() {
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public Builder removeStudents(int index) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.remove(index);
        onChanged();
      } else {
        studentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public uc.mei.is.protos.Student.Builder getStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public uc.mei.is.protos.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);  } else {
        return studentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public java.util.List<? extends uc.mei.is.protos.StudentOrBuilder> 
         getStudentsOrBuilderList() {
      if (studentsBuilder_ != null) {
        return studentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(students_);
      }
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public uc.mei.is.protos.Student.Builder addStudentsBuilder() {
      return getStudentsFieldBuilder().addBuilder(
          uc.mei.is.protos.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public uc.mei.is.protos.Student.Builder addStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().addBuilder(
          index, uc.mei.is.protos.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Student students = 6;</code>
     */
    public java.util.List<uc.mei.is.protos.Student.Builder> 
         getStudentsBuilderList() {
      return getStudentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.protos.Student, uc.mei.is.protos.Student.Builder, uc.mei.is.protos.StudentOrBuilder> 
        getStudentsFieldBuilder() {
      if (studentsBuilder_ == null) {
        studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.protos.Student, uc.mei.is.protos.Student.Builder, uc.mei.is.protos.StudentOrBuilder>(
                students_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        students_ = null;
      }
      return studentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.Teacher)
  }

  // @@protoc_insertion_point(class_scope:model.Teacher)
  private static final uc.mei.is.protos.Teacher DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.protos.Teacher();
  }

  public static uc.mei.is.protos.Teacher getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Teacher>
      PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
    @java.lang.Override
    public Teacher parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Teacher(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Teacher> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Teacher> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.protos.Teacher getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

