// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.protos;

/**
 * Protobuf type {@code model.Timestamp}
 */
public final class Timestamp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.Timestamp)
    TimestampOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Timestamp.newBuilder() to construct.
  private Timestamp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Timestamp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Timestamp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Timestamp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            year_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            month_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            day_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            hour_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            minute_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            second_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.protos.School.internal_static_model_Timestamp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.protos.School.internal_static_model_Timestamp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.protos.Timestamp.class, uc.mei.is.protos.Timestamp.Builder.class);
  }

  private int bitField0_;
  public static final int YEAR_FIELD_NUMBER = 1;
  private int year_;
  /**
   * <code>required int32 year = 1;</code>
   * @return Whether the year field is set.
   */
  @java.lang.Override
  public boolean hasYear() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 year = 1;</code>
   * @return The year.
   */
  @java.lang.Override
  public int getYear() {
    return year_;
  }

  public static final int MONTH_FIELD_NUMBER = 2;
  private int month_;
  /**
   * <code>required int32 month = 2;</code>
   * @return Whether the month field is set.
   */
  @java.lang.Override
  public boolean hasMonth() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 month = 2;</code>
   * @return The month.
   */
  @java.lang.Override
  public int getMonth() {
    return month_;
  }

  public static final int DAY_FIELD_NUMBER = 3;
  private int day_;
  /**
   * <code>required int32 day = 3;</code>
   * @return Whether the day field is set.
   */
  @java.lang.Override
  public boolean hasDay() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 day = 3;</code>
   * @return The day.
   */
  @java.lang.Override
  public int getDay() {
    return day_;
  }

  public static final int HOUR_FIELD_NUMBER = 4;
  private int hour_;
  /**
   * <code>required int32 hour = 4;</code>
   * @return Whether the hour field is set.
   */
  @java.lang.Override
  public boolean hasHour() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required int32 hour = 4;</code>
   * @return The hour.
   */
  @java.lang.Override
  public int getHour() {
    return hour_;
  }

  public static final int MINUTE_FIELD_NUMBER = 5;
  private int minute_;
  /**
   * <code>required int32 minute = 5;</code>
   * @return Whether the minute field is set.
   */
  @java.lang.Override
  public boolean hasMinute() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required int32 minute = 5;</code>
   * @return The minute.
   */
  @java.lang.Override
  public int getMinute() {
    return minute_;
  }

  public static final int SECOND_FIELD_NUMBER = 6;
  private int second_;
  /**
   * <code>required int32 second = 6;</code>
   * @return Whether the second field is set.
   */
  @java.lang.Override
  public boolean hasSecond() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required int32 second = 6;</code>
   * @return The second.
   */
  @java.lang.Override
  public int getSecond() {
    return second_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasYear()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMonth()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDay()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasHour()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMinute()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSecond()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, year_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, month_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, day_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, hour_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, minute_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, second_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, year_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, month_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, day_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, hour_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, minute_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, second_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.protos.Timestamp)) {
      return super.equals(obj);
    }
    uc.mei.is.protos.Timestamp other = (uc.mei.is.protos.Timestamp) obj;

    if (hasYear() != other.hasYear()) return false;
    if (hasYear()) {
      if (getYear()
          != other.getYear()) return false;
    }
    if (hasMonth() != other.hasMonth()) return false;
    if (hasMonth()) {
      if (getMonth()
          != other.getMonth()) return false;
    }
    if (hasDay() != other.hasDay()) return false;
    if (hasDay()) {
      if (getDay()
          != other.getDay()) return false;
    }
    if (hasHour() != other.hasHour()) return false;
    if (hasHour()) {
      if (getHour()
          != other.getHour()) return false;
    }
    if (hasMinute() != other.hasMinute()) return false;
    if (hasMinute()) {
      if (getMinute()
          != other.getMinute()) return false;
    }
    if (hasSecond() != other.hasSecond()) return false;
    if (hasSecond()) {
      if (getSecond()
          != other.getSecond()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasYear()) {
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
    }
    if (hasMonth()) {
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
    }
    if (hasDay()) {
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
    }
    if (hasHour()) {
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
    }
    if (hasMinute()) {
      hash = (37 * hash) + MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getMinute();
    }
    if (hasSecond()) {
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getSecond();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.protos.Timestamp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Timestamp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Timestamp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.protos.Timestamp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.protos.Timestamp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.Timestamp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.Timestamp)
      uc.mei.is.protos.TimestampOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.protos.School.internal_static_model_Timestamp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.protos.School.internal_static_model_Timestamp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.protos.Timestamp.class, uc.mei.is.protos.Timestamp.Builder.class);
    }

    // Construct using uc.mei.is.protos.Timestamp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      year_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      month_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      day_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      hour_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      minute_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      second_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.protos.School.internal_static_model_Timestamp_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.protos.Timestamp getDefaultInstanceForType() {
      return uc.mei.is.protos.Timestamp.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.protos.Timestamp build() {
      uc.mei.is.protos.Timestamp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.protos.Timestamp buildPartial() {
      uc.mei.is.protos.Timestamp result = new uc.mei.is.protos.Timestamp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.year_ = year_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.month_ = month_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.day_ = day_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hour_ = hour_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.minute_ = minute_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.second_ = second_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.protos.Timestamp) {
        return mergeFrom((uc.mei.is.protos.Timestamp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.protos.Timestamp other) {
      if (other == uc.mei.is.protos.Timestamp.getDefaultInstance()) return this;
      if (other.hasYear()) {
        setYear(other.getYear());
      }
      if (other.hasMonth()) {
        setMonth(other.getMonth());
      }
      if (other.hasDay()) {
        setDay(other.getDay());
      }
      if (other.hasHour()) {
        setHour(other.getHour());
      }
      if (other.hasMinute()) {
        setMinute(other.getMinute());
      }
      if (other.hasSecond()) {
        setSecond(other.getSecond());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasYear()) {
        return false;
      }
      if (!hasMonth()) {
        return false;
      }
      if (!hasDay()) {
        return false;
      }
      if (!hasHour()) {
        return false;
      }
      if (!hasMinute()) {
        return false;
      }
      if (!hasSecond()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.protos.Timestamp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.protos.Timestamp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int year_ ;
    /**
     * <code>required int32 year = 1;</code>
     * @return Whether the year field is set.
     */
    @java.lang.Override
    public boolean hasYear() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 year = 1;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }
    /**
     * <code>required int32 year = 1;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(int value) {
      bitField0_ |= 0x00000001;
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 year = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      bitField0_ = (bitField0_ & ~0x00000001);
      year_ = 0;
      onChanged();
      return this;
    }

    private int month_ ;
    /**
     * <code>required int32 month = 2;</code>
     * @return Whether the month field is set.
     */
    @java.lang.Override
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 month = 2;</code>
     * @return The month.
     */
    @java.lang.Override
    public int getMonth() {
      return month_;
    }
    /**
     * <code>required int32 month = 2;</code>
     * @param value The month to set.
     * @return This builder for chaining.
     */
    public Builder setMonth(int value) {
      bitField0_ |= 0x00000002;
      month_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 month = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      month_ = 0;
      onChanged();
      return this;
    }

    private int day_ ;
    /**
     * <code>required int32 day = 3;</code>
     * @return Whether the day field is set.
     */
    @java.lang.Override
    public boolean hasDay() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 day = 3;</code>
     * @return The day.
     */
    @java.lang.Override
    public int getDay() {
      return day_;
    }
    /**
     * <code>required int32 day = 3;</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(int value) {
      bitField0_ |= 0x00000004;
      day_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 day = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      bitField0_ = (bitField0_ & ~0x00000004);
      day_ = 0;
      onChanged();
      return this;
    }

    private int hour_ ;
    /**
     * <code>required int32 hour = 4;</code>
     * @return Whether the hour field is set.
     */
    @java.lang.Override
    public boolean hasHour() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 hour = 4;</code>
     * @return The hour.
     */
    @java.lang.Override
    public int getHour() {
      return hour_;
    }
    /**
     * <code>required int32 hour = 4;</code>
     * @param value The hour to set.
     * @return This builder for chaining.
     */
    public Builder setHour(int value) {
      bitField0_ |= 0x00000008;
      hour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 hour = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHour() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hour_ = 0;
      onChanged();
      return this;
    }

    private int minute_ ;
    /**
     * <code>required int32 minute = 5;</code>
     * @return Whether the minute field is set.
     */
    @java.lang.Override
    public boolean hasMinute() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 minute = 5;</code>
     * @return The minute.
     */
    @java.lang.Override
    public int getMinute() {
      return minute_;
    }
    /**
     * <code>required int32 minute = 5;</code>
     * @param value The minute to set.
     * @return This builder for chaining.
     */
    public Builder setMinute(int value) {
      bitField0_ |= 0x00000010;
      minute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 minute = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinute() {
      bitField0_ = (bitField0_ & ~0x00000010);
      minute_ = 0;
      onChanged();
      return this;
    }

    private int second_ ;
    /**
     * <code>required int32 second = 6;</code>
     * @return Whether the second field is set.
     */
    @java.lang.Override
    public boolean hasSecond() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 second = 6;</code>
     * @return The second.
     */
    @java.lang.Override
    public int getSecond() {
      return second_;
    }
    /**
     * <code>required int32 second = 6;</code>
     * @param value The second to set.
     * @return This builder for chaining.
     */
    public Builder setSecond(int value) {
      bitField0_ |= 0x00000020;
      second_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 second = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecond() {
      bitField0_ = (bitField0_ & ~0x00000020);
      second_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.Timestamp)
  }

  // @@protoc_insertion_point(class_scope:model.Timestamp)
  private static final uc.mei.is.protos.Timestamp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.protos.Timestamp();
  }

  public static uc.mei.is.protos.Timestamp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Timestamp>
      PARSER = new com.google.protobuf.AbstractParser<Timestamp>() {
    @java.lang.Override
    public Timestamp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Timestamp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Timestamp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Timestamp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.protos.Timestamp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

