// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.protos;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 year = 1;</code>
   * @return Whether the year field is set.
   */
  boolean hasYear();
  /**
   * <code>required int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>required int32 month = 2;</code>
   * @return Whether the month field is set.
   */
  boolean hasMonth();
  /**
   * <code>required int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>required int32 day = 3;</code>
   * @return Whether the day field is set.
   */
  boolean hasDay();
  /**
   * <code>required int32 day = 3;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>required int32 hour = 4;</code>
   * @return Whether the hour field is set.
   */
  boolean hasHour();
  /**
   * <code>required int32 hour = 4;</code>
   * @return The hour.
   */
  int getHour();

  /**
   * <code>required int32 minute = 5;</code>
   * @return Whether the minute field is set.
   */
  boolean hasMinute();
  /**
   * <code>required int32 minute = 5;</code>
   * @return The minute.
   */
  int getMinute();

  /**
   * <code>required int32 second = 6;</code>
   * @return Whether the second field is set.
   */
  boolean hasSecond();
  /**
   * <code>required int32 second = 6;</code>
   * @return The second.
   */
  int getSecond();
}
