// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.model.proto;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Teacher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Teacher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_School_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_School_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\005model\"\227\001\n\007Student\022\n\n\002id\030\001" +
      " \002(\005\022\017\n\007teacher\030\002 \001(\005\022\014\n\004name\030\003 \002(\t\022\023\n\013p" +
      "honeNumber\030\004 \002(\005\022\017\n\007address\030\005 \002(\t\022\016\n\006gen" +
      "der\030\006 \002(\t\022\021\n\tbirthDate\030\007 \002(\t\022\030\n\020registra" +
      "tionDate\030\010 \002(\t\"m\n\007Teacher\022\n\n\002id\030\001 \002(\005\022\017\n" +
      "\007student\030\002 \003(\005\022\014\n\004name\030\003 \002(\t\022\023\n\013phoneNum" +
      "ber\030\004 \002(\005\022\021\n\tbirthDate\030\005 \002(\t\022\017\n\007address\030" +
      "\006 \002(\t\"J\n\006School\022\037\n\007teacher\030\001 \003(\0132\016.model" +
      ".Teacher\022\037\n\007student\030\002 \003(\0132\016.model.Studen" +
      "tB \n\025uc.mei.is.model.protoB\005ModelP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_model_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Student_descriptor,
        new java.lang.String[] { "Id", "Teacher", "Name", "PhoneNumber", "Address", "Gender", "BirthDate", "RegistrationDate", });
    internal_static_model_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Teacher_descriptor,
        new java.lang.String[] { "Id", "Student", "Name", "PhoneNumber", "BirthDate", "Address", });
    internal_static_model_School_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_School_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_School_descriptor,
        new java.lang.String[] { "Teacher", "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
