// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.model.proto;

public interface SchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.School)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  java.util.List<uc.mei.is.model.proto.Teacher> 
      getTeacherList();
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  uc.mei.is.model.proto.Teacher getTeacher(int index);
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  int getTeacherCount();
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  java.util.List<? extends uc.mei.is.model.proto.TeacherOrBuilder> 
      getTeacherOrBuilderList();
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  uc.mei.is.model.proto.TeacherOrBuilder getTeacherOrBuilder(
      int index);

  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  java.util.List<uc.mei.is.model.proto.Student> 
      getStudentList();
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  uc.mei.is.model.proto.Student getStudent(int index);
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  java.util.List<? extends uc.mei.is.model.proto.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  uc.mei.is.model.proto.StudentOrBuilder getStudentOrBuilder(
      int index);
}
