// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.model.proto;

/**
 * Protobuf type {@code model.School}
 */
public final class School extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.School)
    SchoolOrBuilder {
private static final long serialVersionUID = 0L;
  // Use School.newBuilder() to construct.
  private School(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private School() {
    teacher_ = java.util.Collections.emptyList();
    student_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new School();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private School(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              teacher_ = new java.util.ArrayList<uc.mei.is.model.proto.Teacher>();
              mutable_bitField0_ |= 0x00000001;
            }
            teacher_.add(
                input.readMessage(uc.mei.is.model.proto.Teacher.PARSER, extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              student_ = new java.util.ArrayList<uc.mei.is.model.proto.Student>();
              mutable_bitField0_ |= 0x00000002;
            }
            student_.add(
                input.readMessage(uc.mei.is.model.proto.Student.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        teacher_ = java.util.Collections.unmodifiableList(teacher_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        student_ = java.util.Collections.unmodifiableList(student_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.model.proto.Model.internal_static_model_School_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.model.proto.Model.internal_static_model_School_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.model.proto.School.class, uc.mei.is.model.proto.School.Builder.class);
  }

  public static final int TEACHER_FIELD_NUMBER = 1;
  private java.util.List<uc.mei.is.model.proto.Teacher> teacher_;
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.model.proto.Teacher> getTeacherList() {
    return teacher_;
  }
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.model.proto.TeacherOrBuilder> 
      getTeacherOrBuilderList() {
    return teacher_;
  }
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  @java.lang.Override
  public int getTeacherCount() {
    return teacher_.size();
  }
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  @java.lang.Override
  public uc.mei.is.model.proto.Teacher getTeacher(int index) {
    return teacher_.get(index);
  }
  /**
   * <code>repeated .model.Teacher teacher = 1;</code>
   */
  @java.lang.Override
  public uc.mei.is.model.proto.TeacherOrBuilder getTeacherOrBuilder(
      int index) {
    return teacher_.get(index);
  }

  public static final int STUDENT_FIELD_NUMBER = 2;
  private java.util.List<uc.mei.is.model.proto.Student> student_;
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.model.proto.Student> getStudentList() {
    return student_;
  }
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.model.proto.StudentOrBuilder> 
      getStudentOrBuilderList() {
    return student_;
  }
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  @java.lang.Override
  public int getStudentCount() {
    return student_.size();
  }
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  @java.lang.Override
  public uc.mei.is.model.proto.Student getStudent(int index) {
    return student_.get(index);
  }
  /**
   * <code>repeated .model.Student student = 2;</code>
   */
  @java.lang.Override
  public uc.mei.is.model.proto.StudentOrBuilder getStudentOrBuilder(
      int index) {
    return student_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getTeacherCount(); i++) {
      if (!getTeacher(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getStudentCount(); i++) {
      if (!getStudent(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < teacher_.size(); i++) {
      output.writeMessage(1, teacher_.get(i));
    }
    for (int i = 0; i < student_.size(); i++) {
      output.writeMessage(2, student_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < teacher_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, teacher_.get(i));
    }
    for (int i = 0; i < student_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, student_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.model.proto.School)) {
      return super.equals(obj);
    }
    uc.mei.is.model.proto.School other = (uc.mei.is.model.proto.School) obj;

    if (!getTeacherList()
        .equals(other.getTeacherList())) return false;
    if (!getStudentList()
        .equals(other.getStudentList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTeacherCount() > 0) {
      hash = (37 * hash) + TEACHER_FIELD_NUMBER;
      hash = (53 * hash) + getTeacherList().hashCode();
    }
    if (getStudentCount() > 0) {
      hash = (37 * hash) + STUDENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudentList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.model.proto.School parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.model.proto.School parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.model.proto.School parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.model.proto.School parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.model.proto.School parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.model.proto.School parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.model.proto.School prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.School}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.School)
      uc.mei.is.model.proto.SchoolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.model.proto.Model.internal_static_model_School_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.model.proto.Model.internal_static_model_School_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.model.proto.School.class, uc.mei.is.model.proto.School.Builder.class);
    }

    // Construct using uc.mei.is.model.proto.School.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTeacherFieldBuilder();
        getStudentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (teacherBuilder_ == null) {
        teacher_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        teacherBuilder_.clear();
      }
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        studentBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.model.proto.Model.internal_static_model_School_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.model.proto.School getDefaultInstanceForType() {
      return uc.mei.is.model.proto.School.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.model.proto.School build() {
      uc.mei.is.model.proto.School result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.model.proto.School buildPartial() {
      uc.mei.is.model.proto.School result = new uc.mei.is.model.proto.School(this);
      int from_bitField0_ = bitField0_;
      if (teacherBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          teacher_ = java.util.Collections.unmodifiableList(teacher_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.teacher_ = teacher_;
      } else {
        result.teacher_ = teacherBuilder_.build();
      }
      if (studentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          student_ = java.util.Collections.unmodifiableList(student_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.student_ = student_;
      } else {
        result.student_ = studentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.model.proto.School) {
        return mergeFrom((uc.mei.is.model.proto.School)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.model.proto.School other) {
      if (other == uc.mei.is.model.proto.School.getDefaultInstance()) return this;
      if (teacherBuilder_ == null) {
        if (!other.teacher_.isEmpty()) {
          if (teacher_.isEmpty()) {
            teacher_ = other.teacher_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTeacherIsMutable();
            teacher_.addAll(other.teacher_);
          }
          onChanged();
        }
      } else {
        if (!other.teacher_.isEmpty()) {
          if (teacherBuilder_.isEmpty()) {
            teacherBuilder_.dispose();
            teacherBuilder_ = null;
            teacher_ = other.teacher_;
            bitField0_ = (bitField0_ & ~0x00000001);
            teacherBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTeacherFieldBuilder() : null;
          } else {
            teacherBuilder_.addAllMessages(other.teacher_);
          }
        }
      }
      if (studentBuilder_ == null) {
        if (!other.student_.isEmpty()) {
          if (student_.isEmpty()) {
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStudentIsMutable();
            student_.addAll(other.student_);
          }
          onChanged();
        }
      } else {
        if (!other.student_.isEmpty()) {
          if (studentBuilder_.isEmpty()) {
            studentBuilder_.dispose();
            studentBuilder_ = null;
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000002);
            studentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentFieldBuilder() : null;
          } else {
            studentBuilder_.addAllMessages(other.student_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getTeacherCount(); i++) {
        if (!getTeacher(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getStudentCount(); i++) {
        if (!getStudent(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.model.proto.School parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.model.proto.School) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<uc.mei.is.model.proto.Teacher> teacher_ =
      java.util.Collections.emptyList();
    private void ensureTeacherIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        teacher_ = new java.util.ArrayList<uc.mei.is.model.proto.Teacher>(teacher_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.model.proto.Teacher, uc.mei.is.model.proto.Teacher.Builder, uc.mei.is.model.proto.TeacherOrBuilder> teacherBuilder_;

    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public java.util.List<uc.mei.is.model.proto.Teacher> getTeacherList() {
      if (teacherBuilder_ == null) {
        return java.util.Collections.unmodifiableList(teacher_);
      } else {
        return teacherBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public int getTeacherCount() {
      if (teacherBuilder_ == null) {
        return teacher_.size();
      } else {
        return teacherBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public uc.mei.is.model.proto.Teacher getTeacher(int index) {
      if (teacherBuilder_ == null) {
        return teacher_.get(index);
      } else {
        return teacherBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder setTeacher(
        int index, uc.mei.is.model.proto.Teacher value) {
      if (teacherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeacherIsMutable();
        teacher_.set(index, value);
        onChanged();
      } else {
        teacherBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder setTeacher(
        int index, uc.mei.is.model.proto.Teacher.Builder builderForValue) {
      if (teacherBuilder_ == null) {
        ensureTeacherIsMutable();
        teacher_.set(index, builderForValue.build());
        onChanged();
      } else {
        teacherBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder addTeacher(uc.mei.is.model.proto.Teacher value) {
      if (teacherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeacherIsMutable();
        teacher_.add(value);
        onChanged();
      } else {
        teacherBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder addTeacher(
        int index, uc.mei.is.model.proto.Teacher value) {
      if (teacherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeacherIsMutable();
        teacher_.add(index, value);
        onChanged();
      } else {
        teacherBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder addTeacher(
        uc.mei.is.model.proto.Teacher.Builder builderForValue) {
      if (teacherBuilder_ == null) {
        ensureTeacherIsMutable();
        teacher_.add(builderForValue.build());
        onChanged();
      } else {
        teacherBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder addTeacher(
        int index, uc.mei.is.model.proto.Teacher.Builder builderForValue) {
      if (teacherBuilder_ == null) {
        ensureTeacherIsMutable();
        teacher_.add(index, builderForValue.build());
        onChanged();
      } else {
        teacherBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder addAllTeacher(
        java.lang.Iterable<? extends uc.mei.is.model.proto.Teacher> values) {
      if (teacherBuilder_ == null) {
        ensureTeacherIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, teacher_);
        onChanged();
      } else {
        teacherBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder clearTeacher() {
      if (teacherBuilder_ == null) {
        teacher_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        teacherBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public Builder removeTeacher(int index) {
      if (teacherBuilder_ == null) {
        ensureTeacherIsMutable();
        teacher_.remove(index);
        onChanged();
      } else {
        teacherBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public uc.mei.is.model.proto.Teacher.Builder getTeacherBuilder(
        int index) {
      return getTeacherFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public uc.mei.is.model.proto.TeacherOrBuilder getTeacherOrBuilder(
        int index) {
      if (teacherBuilder_ == null) {
        return teacher_.get(index);  } else {
        return teacherBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public java.util.List<? extends uc.mei.is.model.proto.TeacherOrBuilder> 
         getTeacherOrBuilderList() {
      if (teacherBuilder_ != null) {
        return teacherBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(teacher_);
      }
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public uc.mei.is.model.proto.Teacher.Builder addTeacherBuilder() {
      return getTeacherFieldBuilder().addBuilder(
          uc.mei.is.model.proto.Teacher.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public uc.mei.is.model.proto.Teacher.Builder addTeacherBuilder(
        int index) {
      return getTeacherFieldBuilder().addBuilder(
          index, uc.mei.is.model.proto.Teacher.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Teacher teacher = 1;</code>
     */
    public java.util.List<uc.mei.is.model.proto.Teacher.Builder> 
         getTeacherBuilderList() {
      return getTeacherFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.model.proto.Teacher, uc.mei.is.model.proto.Teacher.Builder, uc.mei.is.model.proto.TeacherOrBuilder> 
        getTeacherFieldBuilder() {
      if (teacherBuilder_ == null) {
        teacherBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.model.proto.Teacher, uc.mei.is.model.proto.Teacher.Builder, uc.mei.is.model.proto.TeacherOrBuilder>(
                teacher_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        teacher_ = null;
      }
      return teacherBuilder_;
    }

    private java.util.List<uc.mei.is.model.proto.Student> student_ =
      java.util.Collections.emptyList();
    private void ensureStudentIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        student_ = new java.util.ArrayList<uc.mei.is.model.proto.Student>(student_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.model.proto.Student, uc.mei.is.model.proto.Student.Builder, uc.mei.is.model.proto.StudentOrBuilder> studentBuilder_;

    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public java.util.List<uc.mei.is.model.proto.Student> getStudentList() {
      if (studentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(student_);
      } else {
        return studentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public int getStudentCount() {
      if (studentBuilder_ == null) {
        return student_.size();
      } else {
        return studentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public uc.mei.is.model.proto.Student getStudent(int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);
      } else {
        return studentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder setStudent(
        int index, uc.mei.is.model.proto.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.set(index, value);
        onChanged();
      } else {
        studentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder setStudent(
        int index, uc.mei.is.model.proto.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder addStudent(uc.mei.is.model.proto.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(value);
        onChanged();
      } else {
        studentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder addStudent(
        int index, uc.mei.is.model.proto.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(index, value);
        onChanged();
      } else {
        studentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder addStudent(
        uc.mei.is.model.proto.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder addStudent(
        int index, uc.mei.is.model.proto.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder addAllStudent(
        java.lang.Iterable<? extends uc.mei.is.model.proto.Student> values) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, student_);
        onChanged();
      } else {
        studentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder clearStudent() {
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        studentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public Builder removeStudent(int index) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.remove(index);
        onChanged();
      } else {
        studentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public uc.mei.is.model.proto.Student.Builder getStudentBuilder(
        int index) {
      return getStudentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public uc.mei.is.model.proto.StudentOrBuilder getStudentOrBuilder(
        int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);  } else {
        return studentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public java.util.List<? extends uc.mei.is.model.proto.StudentOrBuilder> 
         getStudentOrBuilderList() {
      if (studentBuilder_ != null) {
        return studentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(student_);
      }
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public uc.mei.is.model.proto.Student.Builder addStudentBuilder() {
      return getStudentFieldBuilder().addBuilder(
          uc.mei.is.model.proto.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public uc.mei.is.model.proto.Student.Builder addStudentBuilder(
        int index) {
      return getStudentFieldBuilder().addBuilder(
          index, uc.mei.is.model.proto.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .model.Student student = 2;</code>
     */
    public java.util.List<uc.mei.is.model.proto.Student.Builder> 
         getStudentBuilderList() {
      return getStudentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.model.proto.Student, uc.mei.is.model.proto.Student.Builder, uc.mei.is.model.proto.StudentOrBuilder> 
        getStudentFieldBuilder() {
      if (studentBuilder_ == null) {
        studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.model.proto.Student, uc.mei.is.model.proto.Student.Builder, uc.mei.is.model.proto.StudentOrBuilder>(
                student_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        student_ = null;
      }
      return studentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.School)
  }

  // @@protoc_insertion_point(class_scope:model.School)
  private static final uc.mei.is.model.proto.School DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.model.proto.School();
  }

  public static uc.mei.is.model.proto.School getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<School>
      PARSER = new com.google.protobuf.AbstractParser<School>() {
    @java.lang.Override
    public School parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new School(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<School> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<School> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.model.proto.School getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

