// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.model.proto;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional int32 teacher = 2;</code>
   * @return Whether the teacher field is set.
   */
  boolean hasTeacher();
  /**
   * <code>optional int32 teacher = 2;</code>
   * @return The teacher.
   */
  int getTeacher();

  /**
   * <code>required string name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 phoneNumber = 4;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>required int32 phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  int getPhoneNumber();

  /**
   * <code>required string address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>required string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>required string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>required string gender = 6;</code>
   * @return Whether the gender field is set.
   */
  boolean hasGender();
  /**
   * <code>required string gender = 6;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>required string gender = 6;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>required string birthDate = 7;</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>required string birthDate = 7;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>required string birthDate = 7;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>required string registrationDate = 8;</code>
   * @return Whether the registrationDate field is set.
   */
  boolean hasRegistrationDate();
  /**
   * <code>required string registrationDate = 8;</code>
   * @return The registrationDate.
   */
  java.lang.String getRegistrationDate();
  /**
   * <code>required string registrationDate = 8;</code>
   * @return The bytes for registrationDate.
   */
  com.google.protobuf.ByteString
      getRegistrationDateBytes();
}
