// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package uc.mei.is.model.proto;

public interface TeacherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Teacher)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated int32 student = 2;</code>
   * @return A list containing the student.
   */
  java.util.List<java.lang.Integer> getStudentList();
  /**
   * <code>repeated int32 student = 2;</code>
   * @return The count of student.
   */
  int getStudentCount();
  /**
   * <code>repeated int32 student = 2;</code>
   * @param index The index of the element to return.
   * @return The student at the given index.
   */
  int getStudent(int index);

  /**
   * <code>required string name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 phoneNumber = 4;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>required int32 phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  int getPhoneNumber();

  /**
   * <code>required string birthDate = 5;</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>required string birthDate = 5;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>required string birthDate = 5;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>required string address = 6;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>required string address = 6;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>required string address = 6;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
